### ISSUE TITLE
Panic in Opcode::Call

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/cilk#1]
I'm working on compiling JavaScript to cilk-ir with rapidus, and executing by jit/x64/compiler.
And found a curious behavior described below.
Both of the codes work with an interpreter correctly.

Do you have any idea?

This IR works well.
```
liveness: define i32 main(i32) {
label.0:        // pred(), succ(), def(4,1,3), in(), out()
    %1 = alloca i32
    store i32 100, i32* %1
    %3 = load i32* %1
    %4 = call i32 f(i32 %3, )
    ret i32 %4
    ret i32 0

}
liveness: define i32 f(i32) {
label.0:        // pred(), succ(), def(1), in(), out()
    %1 = add i32 %arg.0, i32 1
    ret i32 %1
    ret i32 0

}
vreg:1  reg:None        spill:false
vreg:2  reg:None        spill:false
vreg:3  reg:Some(Register(0))   spill:false
vreg:4  reg:Some(Register(0))   spill:false
vreg:5  reg:None        spill:false
vreg:6  reg:None        spill:false
vreg:1  reg:Some(Register(0))   spill:false
vreg:2  reg:None        spill:false
vreg:3  reg:None        spill:false
exec: Int32(101)
saved register: []
jit: Int32(101)
```

But this goes panic when compiling call instruction.
```
liveness: define i32 main(i32) {
label.0:        // pred(), succ(), def(4,1,3), in(), out()
    %1 = alloca i32
    store i32 100, i32* %1
    %3 = load i32* %1
    %4 = call i32 f(i32 %3, )
    ret i32 0

}
liveness: define i32 f(i32) {
label.0:        // pred(), succ(), def(1), in(), out()
    %1 = add i32 %arg.0, i32 1
    ret i32 %1
    ret i32 0

}
vreg:1  reg:None        spill:false
vreg:2  reg:None        spill:false
vreg:3  reg:Some(Register(0))   spill:false
vreg:4  reg:None        spill:false
vreg:5  reg:None        spill:false
vreg:1  reg:Some(Register(0))   spill:false
vreg:2  reg:None        spill:false
vreg:3  reg:None        spill:false
exec: Int32(0)
saved register: []
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   ...
  11: core::option::Option<T>::unwrap
             at /rustc/dfd52ba6ac2262c6b61c59ec86bfd23e4e53d3de/src/libcore/macros.rs:12
  12: cilk::exec::jit::x64::compiler::JITCompiler::compile
             at cilk/src/exec/jit/x64/compiler.rs:223
  13: rapidus::main
             at rapidus/src/main.rs:83
  ...

```
The JavaScript source codes are here.
```javascript
/// This works.
let x = 100
return f(x)
function f(x) {
  return x + 1
}
/// This fails.
let x = 100
f(x)
function f(x) {
  return x + 1
}
```

**Comment by maekawatoshiki** [comment]
Appreciate your issue. I'm now working on it.

**Comment by maekawatoshiki** [comment]
the test ``func_call2`` in ``./tests/func_call.rs`` works now.

**Comment by sisshiki1969** [comment]
Yes...

This works.
```javascript
// Javascript
let i = 100
return f(i)

function f(x) {
  return x + 1
}

/*
Id { idx: 0 } define i32 main() {
label.0:        // pred(), succ(), def(), in(), out()
    %1 = alloca i32
    store i32 100, i32* %1
    %3 = load i32* %1
    %4 = call i32 f(i32 %3, )
    ret i32 %4
    ret i32 0

}
Id { idx: 1 } define i32 f(i32) {
label.0:        // pred(), succ(), def(), in(), out()
    %1 = add i32 %arg.0, i32 1
    ret i32 %1
    ret i32 0
}
=> jit: Int32(101)
**/
```
This fails. It seems something wrong in register allocation...
```javascript
// Javascript
let i = 100
f(i)
return 100

function f(x) {
  return x + 1
}

/*
Id { idx: 0 } define i32 main() {
label.0:        // pred(), succ(), def(), in(), out()
    %1 = alloca i32
    store i32 100, i32* %1
    %3 = load i32* %1
    %4 = call i32 f(i32 %3, )
    ret i32 100
    ret i32 0
}
Id { idx: 1 } define i32 f(i32) {
label.0:        // pred(), succ(), def(), in(), out()
    %1 = add i32 %arg.0, i32 1
    ret i32 %1
    ret i32 0
}
=>
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   ...
  10: <alloc::vec::SetLenOnDrop as core::ops::drop::Drop>::drop
             at cilk/src/exec/jit/x64/compiler.rs:222
  11: <alloc::vec::SetLenOnDrop as core::ops::drop::Drop>::drop
             at cilk/src/exec/jit/x64/compiler.rs:96
  12: rapidus::main
             at rapidus/src/main.rs:78
   ...
**/
```

**Comment by maekawatoshiki** [comment]
I reproduced the problem and found the solution

**Comment by maekawatoshiki** [comment]
See the commit, please.

**Comment by sisshiki1969** [comment]
Now it works. Thanks!
